import type { Metadata } from "next";
import {
  Audiowide,
  Merriweather,
  Roboto,
  Source_Serif_4,
} from "next/font/google";
import "./globals.css";

import "katex/dist/katex.min.css";
import "@/styles/katex-overrides.css";
import "@/styles/tiptap.css";
import "@/styles/hljs.css";

import { ThemeProvider } from "@/components/theme-provider";
import { ThemeShortcut } from "@/components/theme-shortcut";
import { TooltipProvider } from "@/components/ui/tooltip";
import { CollaboratorManagerProvider } from "@/contex/CollaboratorManagerContext";
import { CollaboratorsDialog } from "@/components/CollaboratorsDialog";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardHeader from "@/components/DashboardHeader";
import AppSidebar from "@/components/dashboard/AppSidebar";
import { AuthProvider } from "@/components/providers/auth-provider";

import { Toaster } from "sonner";

// Google Fonts
const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-audiowide",
});
const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-merriweather",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--font-roboto",
});
const sourceSerif4 = Source_Serif_4({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
  variable: "--font-source-serif-4",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${audiowide.variable} 
          ${merriweather.variable} 
          ${roboto.variable} 
          ${sourceSerif4.variable} 
          antialiased
        `}
      >
        <AuthProvider>
          <ThemeProvider defaultTheme="system" storageKey="theme">
            <ThemeShortcut />
            <CollaboratorManagerProvider>
              <TooltipProvider>
                <CollaboratorsDialog />
                <SidebarProvider>
                  <AppSidebar />
                  <SidebarInset>
                    <DashboardHeader />
                    {children}
                  </SidebarInset>
                </SidebarProvider>
              </TooltipProvider>
            </CollaboratorManagerProvider>
            
            <Toaster/>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
