import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "katex/dist/katex.min.css";
import "@/styles/katex-overrides.css";
// import "@/styles/theme.css";
import "@/styles/tiptap.css";
import "@/styles/hljs.css";

import { ThemeProvider } from "@/components/theme-provider";
import { ThemeShortcut } from "@/components/theme-shortcut";
import { TooltipProvider } from "@/components/ui/tooltip";
import { CollaboratorManagerProvider } from "@/contex/CollaboratorManagerContext";
import { CollaboratorsDialog } from "@/components/CollaboratorsDialog";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import DashboardHeader from "@/components/DashboardHeader";
import { Separator } from "@/components/ui/separator";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import AppSidebar from "@/components/dashboard/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          defaultTheme="system"
          enableSystem
          storageKey="theme" // ✅ FIXED
        >
          <ThemeShortcut />
          <CollaboratorManagerProvider>
            <TooltipProvider>
              <CollaboratorsDialog />
              <SidebarProvider>
                 <AppSidebar />
                <SidebarInset>
                  <DashboardHeader />
                  {children}
                </SidebarInset>
              </SidebarProvider>
            </TooltipProvider>
          </CollaboratorManagerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
